services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - ./kafka/zookeeper_data/zookeeper_data:/var/lib/zookeeper/data
      - ./kafka/zookeeper_data/zookeeper_log:/var/lib/zookeeper/log
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2181" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./kafka/kafka-data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    network_mode: "host"
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    env_file:
      - .env

  core:
    depends_on:
      kafka:
        condition: service_healthy
    build:
      context: .
      dockerfile: core/Dockerfile
    network_mode: "host"
    ports:
      - "${CORE_PORT}:${CORE_PORT}"
    env_file:
      - .env
    environment:
      - CORE_PORT=${CORE_PORT}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_LOCAL=${MONGODB_LOCAL}
      - FRONT_URL=${FRONT_URL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}

  battle-stats:
    depends_on:
      kafka:
        condition: service_healthy
    build:
      context: .
      dockerfile: battle-stats/Dockerfile
    network_mode: "host"
    ports:
      - "${BATTLE_STATS_PORT}:${BATTLE_STATS_PORT}"
    env_file:
      - .env
    environment:
      - BATTLE_STATS_PORT=${BATTLE_STATS_PORT}

  battle:
    depends_on:
      kafka:
        condition: service_healthy
    build:
      context: .
      dockerfile: battle/Dockerfile
    network_mode: "host"
    ports:
      - "${BATTLE_PORT}:${BATTLE_PORT}"
    env_file:
      - .env
    environment:
      - BATTLE_PORT=${BATTLE_PORT}

  battle-websocket:
    depends_on:
      kafka:
        condition: service_healthy
    build:
      context: .
      dockerfile: battle-websocket/Dockerfile
    network_mode: "host"
    ports:
      - "${BATTLE_WEBSOCKET_PORT}:${BATTLE_WEBSOCKET_PORT}"
    env_file:
      - .env
    environment:
      - BATTLE_WEBSOCKET_PORT=${BATTLE_WEBSOCKET_PORT}