export enum PokemonType {
  NORMAL = "NORMAL",
  FIRE = "FIRE",
  WATER = "WATER",
  ELECTRIC = "ELECTRIC",
  GRASS = "GRASS",
  ICE = "ICE",
  FIGHTING = "FIGHTING",
  POISON = "POISON",
  GROUND = "GROUND",
  FLYING = "FLYING",
  PSY = "PSY",
  BUG = "BUG",
  ROCK = "ROCK",
  GHOST = "GHOST",
  DRAGON = "DRAGON",
  DARK = "DARK",
  STEEL = "STEEL",
  FAIRY = "FAIRY",
}
