name: Battle Stats CI

on:
  push:
    branches:
      - master
      - prod
    paths:
      - 'backend/battle-stats/**'
      - 'backend/shared/**'
  pull_request:
    paths:
      - 'backend/battle-stats/**'
      - 'backend/shared/**'

jobs:
  build-shared:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: cd backend/shared && npm ci
      - name: Build Shared
        run: cd backend/shared && npm run build

  build-battle-stats:
    needs: build-shared
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: cd backend/battle-stats && npm ci
      - name: Build Battle Stats
        run: cd backend/battle-stats && npm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint and Format Check
        run: |
          cd backend/battle-stats
          npm ci
          npm run lint:check
          npm run format:check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          cd backend/battle-stats
          npm ci
          npm test -- --coverage
        env:
          CI: true
