name: Deploy to Azure VM

on:
  push:
    branches: [ prod ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ prod ]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Install dependencies
        run: cd backend && npm install

      - name: Build
        run: cd backend && npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to VM and Deploy
        run: rsync -avz --exclude='.env' -e "ssh -o StrictHostKeyChecking=no" ./backend/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.DEPLOY_PATH }}

