name: Frontend CI

on:
  push:
    branches: [ master ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run:
          cd frontend && npm ci --legacy-peer-deps

      - name: Run linter
        run:
          cd frontend && npm run lint:check

      - name: Run formatter
        run:
          cd frontend && npm run format:check

      - name: Build project
        run:
          cd frontend && npm run build
